#!/bin/bash

BASE_PKG() {
sudo xbps-install -Syu -u xbps && sudo xbps-install -Syu
sudo xbps-install -Syu elogind mesa-dri sway Waybar wofi swaylock git vim sakura neofetch arc-theme papirus-icon-theme sakura curl
sudo ln -s /etc/sv/dbus /var/service
}

SWAY_CONF() {
mkdir -p /tmp/swaytmp
export XDG_RUNTIME_DIR=/tmp/swaytmp
sudo chmod +s /usr/bin/sway
chmod +x wm/.config/wofi/*
cp -r wm/. /$HOME/
curl https://raw.githubusercontent.com/yperta/walls/main/wallhaven-pkkvg9.jpg > /$HOME/.config/1.jpg
fc-cache -fv
sway
}

#functions call 
BASE_PKG
SWAY_CONF



